### ISSUE TITLE
How can we handle non-spot data?

### ISSUE THREAD

**Issue by berl** [chanzuckerberg/spatial-warehouse#8]
Some spatial methods use total intensity to quantify expression instead of spot counts. The current schema would allow such data in the `matrix` but doesn't provide any way to describe/handle this kind of data before it is assigned to `observations` ( which are currently "cells" for most applications).

This `intensity_expression` data is identical to image data in structure- @ambrosejcarr do you think we can somehow leverage the `spacetx-format` to corral this kind of data?

**Comment by ambrosejcarr** [comment]
@berl I'd need to see some example data and a link to a workflow in order to suggest how to handle it. Image data _could_ be corralled in `spacetx-format` but I'm thinking it might be too heavyweight solution. It could make more sense to design a 4th object in `starspace` that's designed to cover single images (including low-zoom overview images).

**Comment by berl** [comment]
@ambrosejcarr I think a way to handle overview images is a really good idea. I suppose the right object (with physical coordinates, pixel size, orientation, ??) could be used once for an overview image and many times for a set of tiles for full-resolution intensity data.  

One motivating use case here is something like the published MERFISH data where the Zhuang lab doesn't localize mRNA for non-barcoded genes but quantifies total intensity in cell areas. Same story with quantification of immunolabeling.  In these scenarios you could have an instance of the 4thObject for each non-barcoded gene (or antibody) that would describe a single stitched image. 

PRO:
- easy to understand (human readable, presumably someone can open the image in FIJI, etc)
- trivial to get from physical coordinates of cells to corresponding location
- simple to visualize cell location with images
CON:
- puts stitching requirement onto data generators when in many cases the actual data is processed in tiles/FOVs.  For example, we only stitch images for visualization, not processing.
- makes loading/saving the image data potentially difficult for large images
- may not really be the raw data by the time it's stitched and fused 


Alternatives:
- A single 4thObject for each FOV  (essentially `spacetx-format`)
- A single 4thObject referring to a collection of FOVs, possibly in a format like .hdf5, .n5, etc.
- ideas?

**Comment by berl** [comment]
@ambrosejcarr  per our discussion, I'm going to close this issue. 

Basic conclusion for those following along:
- this analyzed data schema doesn't and shouldn't cover raw data.  
- "expression images" that might underlie the expression values in cell x gene tables from some experiments are very close to raw data and should be available as such.  
- processing operations such as normalization and stitching (for example) could be specified to allow traceability between raw data and the expression values associated with segmented cells
